#!/bin/sh
# Editor
if (( $+commands[nvim] )); then
	alias vi="nvim"
elif (( $+commands[vim] )); then
	alias vi="vim"
else
	alias vi="vi"
fi
alias em="emacsclient"

# Workspace
alias ws="$HOME/.config/scripts/tmux2"
alias nvimrc='vi ~/.config/nvim/'

# Python
alias python=python3
alias py=python3
alias pip=pip3
alias pya=". ./venv/bin/activate"
alias pyd="deactivate"

# Lua
stylua="stylua --indent-type=Spaces --indent-width=2 --line-endings=unix --quote-style=AutoPreferDouble"

# Config alias
alias zshconfig="vi $ZDOTDIR/.zshrc"
alias zshsource="source $ZDOTDIR/.zshrc"

# Update plugins
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'
alias free='free -m'

# Directory
if which eza > /dev/null; then
	alias ls="eza --group-directories-first --no-user"
	alias l="eza -la --icons --group-directories-first --no-user"
	alias ll="eza -l --icons --group-directories-first --no-user"
else
	export LSCOLORS="Gxfxcxdxbxegedabagacad"
	alias ls='ls -G'
	alias lsa='ls -lah'
	alias l='ls -lah'
	alias ll='ls -lh'
	alias la='ls -lAh'
fi

setopt auto_pushd
setopt pushd_ignore_dups
setopt pushdminus
alias -- -='\cd -'
alias 1='\cd -'
alias 2='\cd -2'
alias 3='\cd -3'
alias 4='\cd -4'
alias 5='\cd -5'
alias 6='\cd -6'
alias 7='\cd -7'
alias 8='\cd -8'
alias 9='\cd -9'

# dir history with fzf
function d () {
  if which fzf > /dev/null; then
    local sel=$(dirs -v | fzf --height=10 | awk '{print $2}')
    echo "${sel}"
    sel=$(eval echo "${sel}")
    if [[ -n "${sel}" ]]; then
      cd "${sel}"
    fi
  else
    dirs -v | head -10
  fi
}

# Git
alias gst='git status'
alias glg='git log'
alias gn='nvim -c "Neogit"'

if which diff-so-fancy > /dev/null; then
	dsf() {
		diff -u $1 $2 | diff-so-fancy
	}
else
	# meh
fi
