#!/bin/sh
if (( $+commands[nvim] )); then
	export EDITOR=nvim
	export MANPAGER='nvim +Man!'
	export MANWIDTH=999
elif (( $+commands[vim] )); then
	export EDITOR=vim
else
	export EDITOR=vi
fi
export PATH="$HOME/.local/bin":"$HOME/.config/scripts":$PATH
#eval "$(zoxide init zsh)"
export PYENV_ROOT="$HOME/.config/pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
[ -f "$PYENV_ROOT/bin/pyenv" ] && eval "$(pyenv init --path)" && eval "$(pyenv init -)"
# eval "`pip completion --zsh`"
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin/

# Rust env
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
	eval "$__conda_setup"
else
	if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
		"$HOME/.miniconda/etc/profile.d/conda.sh"
	else
		export PATH="$HOME/.miniconda/bin:$PATH"
	fi
fi
unset __conda_setup
# <<< conda initialize <<<

export RIPGREP_CONFIG_PATH=$XDG_DATA_HOME/rg/ripgreprc
