#!/bin/sh
if which nvim > /dev/null; then
	export EDITOR=nvim
	export MANPAGER='nvim +Man!'
	export MANWIDTH=999
else
	export EDITOR=vim
fi
export PATH="$HOME/.local/bin":"$HOME/.config/scripts":$PATH
#eval "$(zoxide init zsh)"
export PYENV_ROOT="$HOME/.config/pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
[ -f "$PYENV_ROOT/bin/pyenv" ] && eval "$(pyenv init --path)"
# eval "`pip completion --zsh`"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
	eval "$__conda_setup"
else
	if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
		"$HOME/.miniconda/etc/profile.d/conda.sh"
	else
		export PATH="$HOME/.miniconda/bin:$PATH"
	fi
fi
unset __conda_setup
# <<< conda initialize <<<

