#!/bin/sh
if (( $+commands[nvim] )); then
	export EDITOR=nvim
	export MANPAGER='nvim +Man!'
	export MANWIDTH=999
elif (( $+commands[vim] )); then
	export EDITOR=vim
else
	export EDITOR=vi
fi
export PATH="$HOME/.local/bin":"$HOME/.config/scripts":$PATH
#eval "$(zoxide init zsh)"
export PYENV_ROOT="$HOME/.config/pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
[ -f "$PYENV_ROOT/bin/pyenv" ] && eval "$(pyenv init --path)" && eval "$(pyenv init -)"
# eval "`pip completion --zsh`"
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin/

# Rust env
[ -f "$HOME/.cargo/env" ] && source "$HOME/.cargo/env"

export RIPGREP_CONFIG_PATH=$XDG_CONFIG_HOME/rg/ripgreprc

export UV_TOOL_BIN_DIR="$HOME/.local/bin"
