# some useful options (man zshoptions)
setopt autocd extendedglob nomatch menucomplete
setopt interactive_comments
stty stop undef		# Disable ctrl-s to freeze terminal.
zle_highlight=('paste:none')

# beeping is annoying
unsetopt BEEP

# completions
autoload -Uz compinit
zstyle ':completion:*' menu select
# zstyle ':completion::complete:lsof:*' menu yes select
zmodload zsh/complist
setopt nomenucomplete # Don't autopick first match
# compinit
_comp_options+=(globdots)		# Include hidden files.
# Word separators
WORDCHARS=''

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

# Colors
autoload -Uz colors && colors

# Useful Functions
source "$ZDOTDIR/zsh-functions"

# Normal files to source
zsh_add_file "zsh-prompt"
zsh_add_file "zsh-exports"
zsh_add_file "zsh-vim-mode"
zsh_add_file "zsh-omz-goodies"
zsh_add_file "zsh-os-conf"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-history"
[ -f $HOME/.config/zsh-work/nsalias ] && source $HOME/.config/zsh-work/nsalias

# Plugins
# For more plugins: https://github.com/unixorn/awesome-zsh-plugins
# More completions https://github.com/zsh-users/zsh-completions
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"
zsh_add_plugin "hlissner/zsh-autopair"
zsh_add_plugin "zsh-users/zsh-autosuggestions"
# zsh_add_completion "esc/conda-zsh-completion" false

# FZF
source <(fzf --zsh)
export FZF_COMPLETION_TRIGGER='~~'
export FZF_DEFAULT_COMMAND="fd -t f --color=never --hidden \
    -E .git \
    -E .github \
    -E venv \
    -E cscope.out \
    -E cscope.files \
    -E cscope.in.out \
    -E cscope.po.out"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
compinit

# Case insensitive
zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'
unsetopt nomatch # disable annoying nomatch found error
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'
zstyle ':completion:*' use-cache yes
export ZSH_CACHE_DIR=$ZDOTDIR/.cache
zstyle ':completion:*' cache-path $ZSH_CACHE_DIR

# Key-bindings
bindkey -s '^o' 'ranger^M'
bindkey -s '^f' 'fzf_fd^M'
bindkey -s '^g' 'fzf_rg^M'

# opam configuration
[[ ! -r $HOME/.opam/opam-init/init.zsh ]] || source $HOME/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

[ -f $HOME/.config/zsh/zsh-custom-conf ] && source $HOME/.config/zsh/zsh-custom-conf
