#!/usr/bin/env bash

# 1. Search for files using fd
# 2. Open the file in NeoVim
FD_PREFIX="fd --hidden -t f -E .git -E venv -E cscope.out -E cscope.files -E cscope.in.out -E cscope.po.out"
INITIAL_QUERY="${*:-}"
fzf --ansi --disabled --query "$INITIAL_QUERY" \
    --bind "start:reload:$FD_PREFIX {q}" \
    --bind "change:reload:sleep 0.1; $FD_PREFIX {q} || true" \
    --preview 'bat -n --color=always {}' \
    --bind 'enter:become(nvim {}; echo {})' \
    --height 40% --layout reverse --tmux bottom,40%
