#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively restart Ripgrep with reload action
# 3. Open the file in NeoVim
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case --hidden "
INITIAL_QUERY="${*:-}"
fzf --ansi --disabled --query "$INITIAL_QUERY" \
    --bind "start:reload:$RG_PREFIX {q}" \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --delimiter : \
    --preview 'bat -n --color=always {1} --highlight-line {2}' \
    --bind 'enter:become(nvim {1} +{2})' \
    --preview-window '+{2}+3/3,~3' \
    --height ~40% --layout reverse --tmux bottom,40%
