#!/usr/bin/env bash

PATH=$1
BACKUP_PATH=${PATH}/backup_fedora
RSYNC=/usr/bin/rsync

BACKUP_DIRS=(
    "Documents"
    "Calibre Library"
    "Learning"
    "Music"
    "Pictures"
)


for dir in "${BACKUP_DIRS[@]}"; do
    echo \"rsync -aP "${HOME}/${dir}" "${BACKUP_PATH}"/\"
    ${RSYNC} -aP "${HOME}/${dir}" "${BACKUP_PATH}/"
done

${RSYNC} -aP "${HOME}/.config/zsh/.history" "${BACKUP_PATH}/zsh/"
${RSYNC} -aP "${HOME}/.config/zsh/zsh-custom-conf" "${BACKUP_PATH}/zsh/"
${RSYNC} -aP "${HOME}/Videos/Movies/" "${PATH}/Entertainment/Movies/"
${RSYNC} -aP "${HOME}/Videos/TV/" "${PATH}/Entertainment/TV Series/"
