#!/usr/bin/env bash
# Copied from https://github.com/awesome-streamers/awesome-streamerrc/blob/master/ThePrimeagen/tmux2

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=`find ~/code -maxdepth 1 -mindepth 1 -type d`
    selected=`echo "$items" | fzf`
fi

dirname=`basename "$selected"`

tmux switch-client -t "$dirname"
if [[ $? -eq 0 ]]; then
    exit 0
fi

tmux new-session -c "$selected" -d -s "$dirname" && tmux switch-client -t "$dirname" || tmux new -c "$selected" -A -s "$dirname"
